drop table IF EXISTS users, films, friends, likes, genre, mpa, director,
                     film_genres, film_mpa, film_directors, reviews;

create TABLE IF NOT EXISTS users (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	login varchar(55) UNIQUE NOT NULL,
	name varchar(255),
	email varchar(55) UNIQUE NOT NULL,
	birthday date NOT NULL
);

create TABLE IF NOT EXISTS films (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  description varchar(200),
  releaseDate date NOT NULL,
  duration integer NOT NULL
);

create TABLE IF NOT EXISTS friends (
  user_id integer NOT NULL,
  friend_id integer NOT NULL,
  CONSTRAINT friends_user_friend FOREIGN KEY (user_id) REFERENCES users(id) ON delete CASCADE,
  CONSTRAINT friends_friend_user FOREIGN KEY (friend_id) REFERENCES users(id) ON delete CASCADE
);


create TABLE IF NOT EXISTS likes (
  film_id integer NOT NULL,
  user_id integer NOT NULL,
  CONSTRAINT likes_film_id FOREIGN KEY (film_id) REFERENCES films(id) ON delete CASCADE,
  CONSTRAINT likes_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON delete CASCADE
);

create TABLE IF NOT EXISTS genre (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(20) UNIQUE
);

create TABLE IF NOT EXISTS mpa (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(20) UNIQUE
);

create TABLE IF NOT EXISTS director (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) UNIQUE
);

create TABLE IF NOT EXISTS film_genres (
  film_id integer NOT NULL,
  genre_id integer NOT NULL,
  CONSTRAINT film_genres_film_id FOREIGN KEY (film_id) REFERENCES films(id) ON delete CASCADE,
  CONSTRAINT film_genres_genre_id FOREIGN KEY (genre_id) REFERENCES genre(id) ON delete CASCADE
);

create TABLE IF NOT EXISTS film_directors (
  film_id integer NOT NULL,
  director_id integer NOT NULL,
  CONSTRAINT film_directors_film_id FOREIGN KEY (film_id) REFERENCES films(id) ON delete CASCADE,
  CONSTRAINT film_directors_director_id FOREIGN KEY (director_id) REFERENCES director(id) ON delete CASCADE
);

create TABLE IF NOT EXISTS film_mpa (
  film_id integer NOT NULL,
  mpa_id integer NOT NULL,
  CONSTRAINT film_mpa_film_id FOREIGN KEY (film_id) REFERENCES films(id) ON delete CASCADE,
  CONSTRAINT film_mpa_mpa_id FOREIGN KEY (mpa_id) REFERENCES mpa(id) ON delete CASCADE
);

create TABLE IF NOT EXISTS reviews (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content varchar(255),
  is_positive boolean,
  film_id integer NOT NULL,
  user_id integer NOT NULL,
  useful integer DEFAULT 0,
  CONSTRAINT reviews_film_id FOREIGN KEY (film_id) REFERENCES films(id) ON delete CASCADE,
  CONSTRAINT reviews_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON delete CASCADE
);